name: Cloud Run Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup GCP Service Account
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: 'latest'
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: Configure Docker
      run: |
         gcloud auth configure-docker
          
    - name: Build
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/helloworld:latest .

    - name: Push
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/helloworld:latest

    - name: Deploy
      run: |
          gcloud run deploy helloworld \
          --region asia-northeast1 \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/be-eazy-monolith \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }}
  
