name: Production Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Build
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPOSITORY_NAME}}-production:latest .

      - name: Push
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPOSITORY_NAME}}-production:latest

      - name: Deploy
        run: |
          gcloud run deploy ${{ secrets.REPOSITORY_NAME}}-production \
          --region asia-southeast1 \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPOSITORY_NAME}}-production \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }} \
          --memory 512M \
          --set-env-vars APP_NAME=${{ secrets.APP_NAME }} \
          APP_ENV=${{ secrets.APP_ENV }} \
          APP_KEY=${{ secrets.APP_KEY }} \
          APP_DEBUG=${{ secrets.APP_DEBUG }} \
          BROADCAST_DRIVER=${{ secrets.BROADCAST_DRIVER }} \
          CACHE_DRIVER=${{ secrets.CACHE_DRIVER }} \
          QUEUE_CONNECTION=${{ secrets.QUEUE_CONNECTION }} \
          SESSION_DRIVER=${{ secrets.SESSION_DRIVER }} \
          SESSION_LIFETIME=${{ secrets.SESSION_LIFETIME }} \
          API_IMAGE_PROCESSING_SERVICE_URL=${{ secrets.API_IMAGE_PROCESSING_SERVICE_URL }} \
          API_IMAGE_PROCESSING_SERVICE_API_KEY=${{ secrets.API_IMAGE_PROCESSING_SERVICE_API_KEY }}

