name: Production Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit
  build-deploy:
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Configure Docker
        run: |
          gcloud auth configure-docker
      - name: Build
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPOSITORY_NAME}}-${{ secrets.ENV_PRODUCTION }}:latest .
      - name: Push
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPOSITORY_NAME}}-${{ secrets.ENV_PRODUCTION }}:latest
      - name: Deploy
        run: |
          gcloud run deploy ${{ secrets.REPOSITORY_NAME}}-${{ secrets.ENV_PRODUCTION }} \
          --region asia-southeast1 \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPOSITORY_NAME}}-${{ secrets.ENV_PRODUCTION }} \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }} \
          --memory 512M \
          --set-env-vars APP_NAME=${{ secrets.APP_NAME }} \
          --set-env-vars APP_ENV=${{ secrets.APP_ENV }} \
          --set-env-vars APP_KEY=${{ secrets.APP_KEY }} \
          --set-env-vars APP_DEBUG=${{ secrets.APP_DEBUG }} \
          --set-env-vars BROADCAST_DRIVER=${{ secrets.BROADCAST_DRIVER }} \
          --set-env-vars CACHE_DRIVER=${{ secrets.CACHE_DRIVER }} \
          --set-env-vars QUEUE_CONNECTION=${{ secrets.QUEUE_CONNECTION }} \
          --set-env-vars SESSION_DRIVER=${{ secrets.SESSION_DRIVER }} \
          --set-env-vars SESSION_LIFETIME=${{ secrets.SESSION_LIFETIME }} \
          --set-env-vars API_IMAGE_PROCESSING_SERVICE_URL=${{ secrets.API_IMAGE_PROCESSING_SERVICE_URL }} \
          --set-env-vars API_IMAGE_PROCESSING_SERVICE_API_KEY=${{ secrets.API_IMAGE_PROCESSING_SERVICE_API_KEY }}


